# Generated by Django 2.0 on 2022-01-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basketapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basket",
            name="id",
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
