# Generated by Django 3.2.9 on 2022-04-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basketapp", "0002_auto_20220121_1056"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basket",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
