# Generated by Django 3.2.9 on 2022-01-13 13:24

from django.db import migrations


def forwards_func(apps, schema_editor):
    shop_users = apps.get_model("authnapp", "ShopUser")  # Load model for make changes

    # Create new admin user
    shop_users.objects.create(
        pk=1,
        password="pbkdf2_sha256$150000$Poyfal2RNsKa$AAnI/z9WprCunEwku4YKvIU9lJAVNsQ//rH2K9Qy2YY=",
        last_login="2021-10-09T10:32:18.075Z",
        is_superuser=True,
        username="admin",
        first_name="",
        last_name="",
        email="root@ya.ru",
        is_staff=True,
        is_active=True,
        date_joined="2021-10-09T10:30:10.234Z",
        avatar="",
        age=33,
    )


def reverse_func(apps, schema_editor):
    shop_users = apps.get_model("authnapp", "ShopUser")  # Load model for make changes

    # Delete all objects
    shop_users.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0001_initial'),
    ]

    operations = [migrations.RunPython(forwards_func, reverse_func)]
