# Generated by Django 2.0 on 2022-01-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0002_fill_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
