# Generated by Django 3.2.9 on 2022-04-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authnapp", "0003_auto_20220121_1056"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopuser",
            name="first_name",
            field=models.CharField(blank=True, max_length=150, verbose_name="first name"),
        ),
        migrations.AlterField(
            model_name="shopuser",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
