# Generated by Django 3.2.9 on 2022-04-09 17:16

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("authnapp", "0005_user_model_extend"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopuser",
            name="activation_key_expires",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 4, 11, 17, 16, 12, 326970, tzinfo=utc),
                verbose_name="актуальность ключа",
            ),
        ),
    ]
