# Generated by Django 3.2.9 on 2022-04-16 12:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0008_default_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 18, 12, 8, 21, 573472, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
